plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.1.0.cjs

# "lint --fix" error (Resolve error: unable to load resolver "node")
# https://github.com/yarnpkg/berry/issues/1427
packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
